# Determinan
Determinan adalah nilai yang terkait dengan matriks persegi (matriks yang memiliki jumlah baris dan kolom yang sama) yang memberikan informasi tentang sifat geometri, linearitas, dan inversibilitas matriks tersebut. Determinan dinyatakan dengan simbol “det” atau dalam notasi matriks dengan dua garis vertikal di sebelah matriks. Untuk matriks A, determinan biasanya dinyatakan sebagai det(A).

## Sifat Sifat determinant



1. Determinan dari matrix indentitas adalah 1

In [1]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [2]:
import numpy as np
A=np.array([[1,1],[2,4]])
B=np.array([[1,2,3,],[4,5,6],[8,9,0]])
C=np.array([[1,0],[0,1]])
D=np.array([[1,0,0],[0,1,0],[0,0,1]])

In [3]:
print("Matriks C = \n", C, ": determinan nya adalah", np.linalg.det(C))
print()
print("Matriks D = \n", D,": determinan nya adalah", np.linalg.det(D))


Matriks C = 
 [[1 0]
 [0 1]] : determinan nya adalah 1.0

Matriks D = 
 [[1 0 0]
 [0 1 0]
 [0 0 1]] : determinan nya adalah 1.0


In [4]:
E = np.linalg.det(C)
F =np.linalg.det(D)
print(E,F)

1.0 1.0


2.
$
det(C) = det(AB) = de(A).det(B) \\
det(I) = det(A).det(A^{-1}) \\
det(A^{-1}) = 1/det(A) \\
$

In [5]:
A = np.array([[1,1], [2,4]])
B = np.linalg.inv(A)
A1 = np.linalg.det(A)
B1 = np.linalg.det(B)

print("determinan A : ", round(A1))
print("determinan B : ",round(B1))
C = A1*B1
print("det.A x det.B :",round(C))
print(A@B)

determinan A :  2
determinan B :  0
det.A x det.B : 1
[[1. 0.]
 [0. 1.]]


3. Menukar baris pada matriks akan merubah tanda determinan

In [6]:
import numpy as np
D = np.array([[1,4,2], [1,1,1],[3,2,1]])
E = np.linalg.det(D)
F = round(E)
print("determinan matriks D : ",F)

determinan matriks D :  5


In [7]:
D1 = np.array([[1,1,1], [1,4,2],[3,2,1]])
D2 = np.linalg.det(D1)
print("determinan matriks D :", round(D2))

determinan matriks D : -5


4.Jika menukar kolom pada suatu matriks, maka akan mengubah tanda dari determinan.

In [8]:
import numpy as np
D = np.array([[1,4,2], [1,1,1],[3,2,1]])
E = np.linalg.det(D)
F = round(E)
print("matriks D :\n", D)
print("determinan D :", F)
D1 = np.array([[4,1,2], [1,1,1],[2,3,1]])
E1 = np.linalg.det(D1)
F1 = round(E1)
print("matriks D1 :\n", D1)
print("determinan D1:", F1)

matriks D :
 [[1 4 2]
 [1 1 1]
 [3 2 1]]
determinan D : 5
matriks D1 :
 [[4 1 2]
 [1 1 1]
 [2 3 1]]
determinan D1: -5


5. jika matriks memiliki baris kelipatan dari suatu baris atau kolom yang lain pada matriks maka determinan nya sama dengan 0

6. jika matriks memiliki baris kelipatan dari suatu baris atau kolom yang lain pada matriks maka determinan nya sama dengan 0

In [9]:
A = np.array([[1,4,2], [2,8,4], [3,2,1]])
B = np.array([[1,2,1], [4,8,4], [1,4,1]])
detA = np.linalg.det(A)
detB = np.linalg.det(B)
print(detA)
print(detB)

0.0
0.0


7.- determinan A tranpose = determinan A
$$
det(A^T) = det(A)
$$

In [10]:
# det A = det A transpose
import numpy as np
A = np.array([[1,4,2], [1,1,1],[3,2,1]])
A_T = np.transpose(A)
B = np.linalg.det(A)
C = np.linalg.det(A_T)
print("determinan A : \n", round(B))
print("determinan A transpose :\n", round(C))

determinan A : 
 5
determinan A transpose :
 5


8.Matriks segitiga atas : jika dibawah diagonal utama [1,1,1] 
 adalah 0, meskipun diatas diagonal utama tidak nol. Sedangkan Matriks segitiga bawah : jika diatas diagonal utama [1,1,1] adalah 0, meskipun dibawah diagonal utama tidak nol. jika melakukan operasi baris elementer tidak akan merubah determinan matriks tersebut.

In [11]:
import numpy as np 
A = np.array([[1,4,2], [1,1,1],[3,2,1]])
print(A)
A1 = np.linalg.det(A)
print("determinan adalah : ", round(A1))

[[1 4 2]
 [1 1 1]
 [3 2 1]]
determinan adalah :  5


In [12]:
B = RowAdd(A, 0, 1, -1)
print(B)
B1 = np.linalg.det(B)
print("deteminan setelah ada Operasi baris elemen : ", round(B1))

[[ 1.  4.  2.]
 [ 0. -3. -1.]
 [ 3.  2.  1.]]
deteminan setelah ada Operasi baris elemen :  5
