# Sistem dengan tak terhingga penyelsaian


## **menyelesaikan sistem linear menggunakan metode eliminasi gauss**
Eliminasi Gauss, atau metode Gauss, adalah algoritma yang digunakan untuk menyelesaikan sistem persamaan linear. eliminasi Gauss melakukan serangkaian operasi baris dasar untuk "menyederhanakan" baris-baris matriks. Hasil dari bagian ini dapat memberitahu apakah sistem persamaan linear tidak memiliki solusi,atau memiliki tak hingga solusi.

**Ada tiga jenis operasi baris dasar yang dapat dilakukan pada baris matriks tersebut:**

1.Menukar posisi dua baris.

2.Mengalikan suatu baris dengan bukan nol .

3.Menambahkan suatu baris dengan suatu kelipatan dari baris yang lain

 **Contoh penyelsaian sistem linear mengunakan eliminasi gauss**

\begin{align*} 
x_1+2x_2+x_3=11\\  
2x_1-x_2+4x_3=4\\
3x_1+8x_2=38\\
\end{align*}




In [1]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [2]:
import numpy as np
A=np.array([[1,2,1,11],[2,-1,4,4],[3,8,0,38]])
print(A)

[[ 1  2  1 11]
 [ 2 -1  4  4]
 [ 3  8  0 38]]


In [3]:

print(A, "\n")

A1 = RowAdd(A, 0,1,-2)
print(A1, "\n")
A2 = RowAdd(A1, 0, 2, -3)
print(A2, "\n")
A3 = RowScale(A2, 1, -1/5)
print(A3, "\n")
A4 = RowAdd(A3, 1, 2, -2)
print(A4, "\n")
A5 = RowScale(A4, 2, -1/2.2)
print(A5, "\n")


[[ 1  2  1 11]
 [ 2 -1  4  4]
 [ 3  8  0 38]] 

[[  1.   2.   1.  11.]
 [  0.  -5.   2. -18.]
 [  3.   8.   0.  38.]] 

[[  1.   2.   1.  11.]
 [  0.  -5.   2. -18.]
 [  0.   2.  -3.   5.]] 

[[ 1.   2.   1.  11. ]
 [-0.   1.  -0.4  3.6]
 [ 0.   2.  -3.   5. ]] 

[[ 1.   2.   1.  11. ]
 [-0.   1.  -0.4  3.6]
 [ 0.   0.  -2.2 -2.2]] 

[[ 1.   2.   1.  11. ]
 [-0.   1.  -0.4  3.6]
 [-0.  -0.   1.   1. ]] 



\begin{align*} 
x_1+2x_2+x_3=11\\  
-x_3=3.6\\
x_3=1\\
\end{align*}

In [4]:
x3 = 1
x2 = 3.6+(0.4*x3)
x1 = 11-((2*x2)+(1*x3))
print(f"""
x1 = {x1}
x2 =  {x2}
x3 = {x3}
""")



x1 = 2.0
x2 =  4.0
x3 = 1

