# Matriks Transpose
Transpose Matriks atau Matriks Transpose adalah suatu  matriks yang dikerjakan pertukaran antara dimensi kolom dan baris.

**Contoh bentuk matriks transpose**


\begin{matrix}
    \\
    A^= \begin{bmatrix}
        1 & 2 & -3 \\
        4 & -5 & 6 \\
        7 & 8 & -9
    \end{bmatrix}
   A^{T} = \begin{bmatrix}
        1 & 4 & 7 \\
        2 & -5 & 8 \\
        3 & 6 & 9
    \end{bmatrix}
    
    \\
    \\
\end{matrix}

**Karakteristik Matriks Transpose**
1. $(A^{T})^{T}=A$
2. $(A+B)^{T}=A^{T}+B^{T}$
3. $(cA)^{T}=cA^{T}$
4. $(AB)^{T}=B^{T}+A^{T}$


**Objek array numpy memiliki metode bernama transpose**

In [1]:
import numpy as np
A=np.array([[1,2,-3],[4,-5,6],[7,8,-9]])
print(A)

[[ 1  2 -3]
 [ 4 -5  6]
 [ 7  8 -9]]


In [2]:
A = np.array([[1,2,-3],[4,-5,6],[7,8,-9]])
A_T= A.transpose()
print(A)
print('\n')
print(A_T)


[[ 1  2 -3]
 [ 4 -5  6]
 [ 7  8 -9]]


[[ 1  4  7]
 [ 2 -5  8]
 [-3  6 -9]]
