# Aljabar matriks

## **Matriks**
Matriks adalah sekumpulan bilangan yang disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung. Nah, tanda kurungnya ini bisa berupa kurung biasa “( )” atau kurung siku “[ ]”, ya. Suatu matriks diberi nama dengan huruf kapital, seperti A, B, C, dan seterusnya


\begin{matrix}
    \\
    A = \begin{bmatrix}
        1 & 3 \\
        2 & 1
    \end{bmatrix}
    \qquad
    B = \begin{bmatrix}
        3 & 0 & 4 \\
        -1 & -2 & 1
    \end{bmatrix}
    \qquad
    C = \begin{bmatrix}
        1 \\ 
        3 \\
        9
    \end{bmatrix}
    \\
    \\
\end{matrix}

- Dimensi atau ukuran matrix adalah baris x kolim, contoh matriks $B$ memili ukuran $2x3$ 
- Matriks yang hanya memiliki 1 kolom, seperti C, biasa disebut vektor. 
- Elemen matriks dinyatakan dengan huruf kecil dengan subskrip untuk menunjukkan posisi entri dalam matriks.

### Implementasi dengan numpy

In [1]:
import numpy as np
A = np.array([[1, 3],[2,1]])
B = np.array([[3, 0, 4], [-1, -2, 1]])
C = np.array([[-2, 1], [4, 1]])
D = np.array([[2],[6]])
print(B)

[[ 3  0  4]
 [-1 -2  1]]


### **Operasi-operasi matrik**

### **Operasi-operasi matrik**

#### Operasi Penjumlahan Matriks
Operasi matriks yang pertama kita bahas adalah penjumlahan matriks. Operasi matriks adalah penjumlahan 2 matriks yang letak komponennya sama. Sebenarnya, operasi matriks tidak jauh beda dengan operasi penjumlahan pada umumnya, tapi ada syarat matriks bisa dijumlahkan.




 




In [2]:
print("matriks A")
print(A,"\n")
print("matriks C")
print(C,"\n")

ac = A + C
print("hasil matriks A + C")
print(ac)

matriks A
[[1 3]
 [2 1]] 

matriks C
[[-2  1]
 [ 4  1]] 

hasil matriks A + C
[[-1  4]
 [ 6  2]]


#### Operasi Pengurangan Matriks
Sebelumnya kita sudah membahas bagaimana sih operasi penjumlahan matriks. Sekarang, kita akan membahas operasi pengurangan matriks. Sebenarnya, cara pengerjaan penjumlahan dan pengurangan matriks itu konsepnya sama saja, kok. Kamu tinggal mengurangkan masing-masing baris sesuai dengan urutannya. 

In [3]:
print("matriks C")
print(C,"\n")
print("matriks A")
print(A,"\n")

ca = C - A
print("hasil matriks C - A")
print(ca)

matriks C
[[-2  1]
 [ 4  1]] 

matriks A
[[1 3]
 [2 1]] 

hasil matriks C - A
[[-3 -2]
 [ 2  0]]


#### Operasi Perkalian Matriks
1. Operasi Perkalian Matriks dengan Bilangan Real (Skalar)
Perkalian matriks dengan bilangan real (skalar) tidak memiliki persyaratan. Jadi, semua matriks dengan ordo apapun bisa dikalikan dengan bilangan real

In [4]:
# k adalah skalar dan A adalah matrix

k = 2
Ak = k * A
print("matrix A")
print(A,"\n")
print("skalar k")
print(k,"\n")
print("hasil perkalian matriks A dengan skalar k ")
print(Ak, "\n")


matrix A
[[1 3]
 [2 1]] 

skalar k
2 

hasil perkalian matriks A dengan skalar k 
[[2 6]
 [4 2]] 



#### Perkalian 2 matriks,menggunakan perulangan

In [5]:
listA = [
    [9, 5],
    [1, 3],
    [2, 4]
]

listB = [
    [1, 2, 3],
    [3, 2, 1]
]

print("Matriks A", listA, "\n")
print("Matriks B", listB, "\n")

print("Panjang baris dan kolom:")

print("Matriks A")
print(len(listA), len(listA[0]), "\n")

print("Matriks B")
print(len(listB), len(listB[0]), "\n")

# n adalah panjang baris matrix listA
n = len(listA)

# adalah panjang kolom matrix listA dan panjang baris matrix listB
m = len(listA[0])

# p adalah panjang baris matrix listB
p = len(listB[0])

hasil = []
# perulangan terjadi sebanyak panjang baris listA
for i in range(0, n):
    hasil1 = []
    # perulangan terjadi sebanyak panjang baris listB
    for j in range(0, p):
        jumlah = 0
        for k in range(0, m):
            jumlah += listA[i][k] * listB[k][j]
        hasil1.append(jumlah)
    hasil.append(hasil1)

print("Hasil dari perkalian matrix:")
for row in hasil:
    print(row)


Matriks A [[9, 5], [1, 3], [2, 4]] 

Matriks B [[1, 2, 3], [3, 2, 1]] 

Panjang baris dan kolom:
Matriks A
3 2 

Matriks B
2 3 

Hasil dari perkalian matrix:
[24, 28, 32]
[10, 8, 6]
[14, 12, 10]
